import { createContext, useContext, useState, useEffect, ReactNode } from "react";

// ─── Types ───────────────────────────────────────────────
export type ThemeName =
  | "midnightPurple" | "deepOcean" | "dark" | "light"
  | "emeraldNight" | "sunsetWarm" | "rosePink"
  | "arctic" | "sandStorm" | "cyberpunk";

export type Language =
  | "ru" | "en" | "es" | "fr" | "de" | "zh" | "ar"
  | "pt" | "ja" | "ko" | "it" | "tr" | "pl" | "uk" | "kk";

export interface ThemeColors {
  bg: string; panel: string; card: string; inputBg: string; overlay: string;
  border: string; borderLight: string;
  heading: string; text: string; textSecondary: string; textMuted: string;
  accent: string; accentHover: string; accentMuted: string;
  buttonHover: string; userBubble: string; aiBubble: string;
  success: string; error: string; warning: string;
}

// ─── 10 Themes ───────────────────────────────────────────
export const themes: Record<ThemeName, ThemeColors> = {
  midnightPurple: {
    bg: "#0D0B14", panel: "#1A1625", card: "#241E33", inputBg: "#241E33", overlay: "#0D0B14B3",
    border: "#352B4D", borderLight: "#463966",
    heading: "#F3F1F5", text: "#D6D0DB", textSecondary: "#9E93A8", textMuted: "#6F667A",
    accent: "#A855F7", accentHover: "#BD85F9", accentMuted: "#A855F726",
    buttonHover: "#2D2640", userBubble: "#7C3AED", aiBubble: "#2D2640",
    success: "#10B981", error: "#EF4444", warning: "#F59E0B",
  },
  deepOcean: {
    bg: "#0B1120", panel: "#151C2C", card: "#1E293B", inputBg: "#1E293B", overlay: "#0B1120B3",
    border: "#2D3A50", borderLight: "#3B4D68",
    heading: "#F1F5F9", text: "#CBD5E1", textSecondary: "#94A3B8", textMuted: "#64748B",
    accent: "#0EA5E9", accentHover: "#38BDF8", accentMuted: "#0EA5E926",
    buttonHover: "#263449", userBubble: "#0284C7", aiBubble: "#263449",
    success: "#2DD4BF", error: "#F43F5E", warning: "#FB923C",
  },
  dark: {
    bg: "#121212", panel: "#1E1E1E", card: "#2D2D2D", inputBg: "#2D2D2D", overlay: "#000000B3",
    border: "#3F3F3F", borderLight: "#525252",
    heading: "#FFFFFF", text: "#E0E0E0", textSecondary: "#A0A0A0", textMuted: "#666666",
    accent: "#3B82F6", accentHover: "#60A5FA", accentMuted: "#3B82F626",
    buttonHover: "#383838", userBubble: "#2563EB", aiBubble: "#383838",
    success: "#22C55E", error: "#EF4444", warning: "#F59E0B",
  },
  light: {
    bg: "#F3F4F6", panel: "#FFFFFF", card: "#FFFFFF", inputBg: "#E5E7EB", overlay: "#0000004D",
    border: "#D1D5DB", borderLight: "#E5E7EB",
    heading: "#111827", text: "#374151", textSecondary: "#6B7280", textMuted: "#9CA3AF",
    accent: "#2563EB", accentHover: "#1D4ED8", accentMuted: "#2563EB26",
    buttonHover: "#F9FAFB", userBubble: "#3B82F6", aiBubble: "#F3F4F6",
    success: "#059669", error: "#DC2626", warning: "#D97706",
  },
  emeraldNight: {
    bg: "#022C22", panel: "#064E3B", card: "#065F46", inputBg: "#065F46", overlay: "#022C22B3",
    border: "#0F766E", borderLight: "#134E4A",
    heading: "#ECFDF5", text: "#D1FAE5", textSecondary: "#6EE7B7", textMuted: "#34D39980",
    accent: "#10B981", accentHover: "#34D399", accentMuted: "#10B98126",
    buttonHover: "#0D9488", userBubble: "#059669", aiBubble: "#0D9488",
    success: "#34D399", error: "#F43F5E", warning: "#F59E0B",
  },
  sunsetWarm: {
    bg: "#1C1917", panel: "#292524", card: "#44403C", inputBg: "#44403C", overlay: "#1C1917B3",
    border: "#57534E", borderLight: "#78716C",
    heading: "#FFF7ED", text: "#FFEDD5", textSecondary: "#FDBA74", textMuted: "#A8A29E",
    accent: "#F59E0B", accentHover: "#FB923C", accentMuted: "#F59E0B26",
    buttonHover: "#57534E", userBubble: "#EA580C", aiBubble: "#57534E",
    success: "#84CC16", error: "#EF4444", warning: "#F97316",
  },
  rosePink: {
    bg: "#1E1B1D", panel: "#2D242B", card: "#3E303B", inputBg: "#3E303B", overlay: "#1E1B1DB3",
    border: "#523F4E", borderLight: "#6B5266",
    heading: "#FFF1F2", text: "#FFE4E6", textSecondary: "#FDA4AF", textMuted: "#9D8A99",
    accent: "#EC4899", accentHover: "#F472B6", accentMuted: "#EC489926",
    buttonHover: "#523F4E", userBubble: "#DB2777", aiBubble: "#523F4E",
    success: "#10B981", error: "#FF0000", warning: "#F59E0B",
  },
  arctic: {
    bg: "#F0F9FF", panel: "#FFFFFF", card: "#FFFFFF", inputBg: "#E0F2FE", overlay: "#0C4A6E4D",
    border: "#BAE6FD", borderLight: "#E0F2FE",
    heading: "#0C4A6E", text: "#075985", textSecondary: "#0284C7", textMuted: "#7DD3FC",
    accent: "#0EA5E9", accentHover: "#0284C7", accentMuted: "#0EA5E926",
    buttonHover: "#F0F9FF", userBubble: "#0284C7", aiBubble: "#F0F9FF",
    success: "#10B981", error: "#E11D48", warning: "#D97706",
  },
  sandStorm: {
    bg: "#FFFBEB", panel: "#FFFFFF", card: "#FFFFFF", inputBg: "#FEF3C7", overlay: "#451A034D",
    border: "#FDE68A", borderLight: "#FEF3C7",
    heading: "#451A03", text: "#78350F", textSecondary: "#92400E", textMuted: "#B4530980",
    accent: "#D97706", accentHover: "#B45309", accentMuted: "#D9770626",
    buttonHover: "#FFFBEB", userBubble: "#B45309", aiBubble: "#FFFBEB",
    success: "#15803D", error: "#B91C1C", warning: "#A16207",
  },
  cyberpunk: {
    bg: "#09090B", panel: "#18181B", card: "#27272A", inputBg: "#09090B", overlay: "#000000E6",
    border: "#ADFF2F4D", borderLight: "#ADFF2F26",
    heading: "#FFFFFF", text: "#F4F4F5", textSecondary: "#ADFF2F", textMuted: "#ADFF2F80",
    accent: "#ADFF2F", accentHover: "#CCFF33", accentMuted: "#ADFF2F26",
    buttonHover: "#ADFF2F1A", userBubble: "#7FFF00", aiBubble: "#18181B",
    success: "#00FF00", error: "#FF003C", warning: "#FFFF00",
  },
};

// ─── Translations (15 languages) ─────────────────────────
const translations: Record<Language, Record<string, string>> = {
  ru: {
    settings: "Настройки", profile: "Профиль", theme: "Тема", language: "Язык",
    midnightPurple: "Полуночный фиолетовый", deepOcean: "Глубокий океан", dark: "Тёмная", light: "Светлая",
    emeraldNight: "Изумрудная ночь", sunsetWarm: "Тёплый закат", rosePink: "Розовая",
    arctic: "Арктическая", sandStorm: "Песчаная буря", cyberpunk: "Киберпанк",
    typeMessage: "Введите сообщение...", send: "Отправить", copied: "Скопировано!",
    lessonTitle: "Урок: Создание макета", lessonDesc: "Вы научитесь создавать эффективные макеты с помощью современных подходов в дизайне.",
    tasks: "Задачи:", task1: "Изучить основные элементы", task2: "Создать wireframe", task3: "Подготовить прототип в Figma",
    aiTeacher: "AI Учитель", aiTeacherTips: "AI Учитель — Подсказки",
    teacherMsg1: "Добро пожаловать на урок! Сегодня мы изучим основы создания макетов.",
    teacherMsg2: "💡 Совет: Начните с визуальной иерархии.", teacherMsg3: "Не забывайте об отступах.",
    teacherMsg4: "⚠️ Слишком много элементов снижают конверсию.", teacherMsg5: "Отлично! Попробуйте применить правило третей.",
    promptExamples: "Примеры промптов", prompt1: "Создай урок по дизайну", prompt2: "Объясни типографику", prompt3: "Расскажи о теории цвета",
    slide1Title: "Слайд 1", slide1Sub: "Введение", slide1Content: "Добро пожаловать на курс по дизайну.",
    slide1B1: "UI/UX дизайн", slide1B2: "Инструменты", slide1B3: "Визуальная иерархия", slide1B4: "Рабочее пространство",
    slide2Title: "Слайд 2", slide2Sub: "Основные принципы", slide2Content: "Ключевые принципы дизайна.",
    slide2B1: "Контраст", slide2B2: "Сетки", slide2B3: "Близость", slide2B4: "Повторяемость",
    slide3Title: "Слайд 3", slide3Sub: "Практические примеры", slide3Content: "Разберём реальные примеры.",
    slide3B1: "Анализ приложений", slide3B2: "Ваш макет", slide3B3: "Обратная связь AI", slide3B4: "Итоговое задание",
    keyTopics: "Ключевые темы:", slideIllustration: "Иллюстрация", prev: "Назад", next: "Далее",
    metrics: "Метрики", detailedMetrics: "Подробные метрики",
    overallProgress: "Общий прогресс", answerAccuracy: "Точность ответов", speed: "Скорость", creativity: "Креативность",
    teacherScore: "Оценка учителя", teacherFeedback: "Хорошая работа! Рекомендую уделить внимание типографике.",
    lessons: "Уроки", lesson1: "Основы макета", lesson2: "Типографика", lesson3: "Теория цвета", lesson4: "UI компоненты", lesson5: "Адаптивный дизайн",
    modelFast: "Быстрый", modelPrecise: "Точный", modelAdvanced: "Продвинутый", modelBalanced: "Сбалансированный",
    teacherAnalyzing: "Учитель анализирует ваш прогресс...",
  },
  en: {
    settings: "Settings", profile: "Profile", theme: "Theme", language: "Language",
    midnightPurple: "Midnight Purple", deepOcean: "Deep Ocean", dark: "Dark", light: "Light",
    emeraldNight: "Emerald Night", sunsetWarm: "Sunset Warm", rosePink: "Rose Pink",
    arctic: "Arctic", sandStorm: "Sand Storm", cyberpunk: "Cyberpunk",
    typeMessage: "Type a message...", send: "Send", copied: "Copied!",
    lessonTitle: "Lesson: Layout Creation", lessonDesc: "Learn to create effective layouts with modern design approaches.",
    tasks: "Tasks:", task1: "Study basic elements", task2: "Create a wireframe", task3: "Prepare Figma prototype",
    aiTeacher: "AI Teacher", aiTeacherTips: "AI Teacher — Tips",
    teacherMsg1: "Welcome to the lesson! Today we'll cover layout basics.",
    teacherMsg2: "💡 Tip: Start with visual hierarchy.", teacherMsg3: "Don't forget about margins.",
    teacherMsg4: "⚠️ Too many elements reduce conversion.", teacherMsg5: "Great! Try applying the rule of thirds.",
    promptExamples: "Prompt Examples", prompt1: "Create a design lesson", prompt2: "Explain typography", prompt3: "Tell about color theory",
    slide1Title: "Slide 1", slide1Sub: "Introduction", slide1Content: "Welcome to the design course.",
    slide1B1: "UI/UX Design", slide1B2: "Tools", slide1B3: "Visual Hierarchy", slide1B4: "Workspace",
    slide2Title: "Slide 2", slide2Sub: "Core Principles", slide2Content: "Key design principles.",
    slide2B1: "Contrast", slide2B2: "Grids", slide2B3: "Proximity", slide2B4: "Repetition",
    slide3Title: "Slide 3", slide3Sub: "Practical Examples", slide3Content: "Let's analyze real examples.",
    slide3B1: "App Analysis", slide3B2: "Your Layout", slide3B3: "AI Feedback", slide3B4: "Final Task",
    keyTopics: "Key Topics:", slideIllustration: "Illustration", prev: "Previous", next: "Next",
    metrics: "Metrics", detailedMetrics: "Detailed Metrics",
    overallProgress: "Overall Progress", answerAccuracy: "Answer Accuracy", speed: "Speed", creativity: "Creativity",
    teacherScore: "Teacher Score", teacherFeedback: "Good work! I recommend focusing on typography.",
    lessons: "Lessons", lesson1: "Layout Basics", lesson2: "Typography", lesson3: "Color Theory", lesson4: "UI Components", lesson5: "Responsive Design",
    modelFast: "Fast", modelPrecise: "Precise", modelAdvanced: "Advanced", modelBalanced: "Balanced",
    teacherAnalyzing: "Teacher is analyzing your progress...",
  },
  es: {
    settings: "Configuración", profile: "Perfil", theme: "Tema", language: "Idioma",
    midnightPurple: "Púrpura medianoche", deepOcean: "Océano profundo", dark: "Oscuro", light: "Claro",
    emeraldNight: "Noche esmeralda", sunsetWarm: "Atardecer cálido", rosePink: "Rosa",
    arctic: "Ártico", sandStorm: "Tormenta de arena", cyberpunk: "Cyberpunk",
    typeMessage: "Escribe un mensaje...", send: "Enviar", copied: "¡Copiado!",
    lessonTitle: "Lección: Creación de diseño", lessonDesc: "Aprenderás a crear diseños efectivos.",
    tasks: "Tareas:", task1: "Estudiar elementos básicos", task2: "Crear wireframe", task3: "Preparar prototipo en Figma",
    aiTeacher: "Profesor IA", aiTeacherTips: "Profesor IA — Consejos",
    teacherMsg1: "¡Bienvenido a la lección!", teacherMsg2: "💡 Consejo: Comienza con la jerarquía visual.",
    teacherMsg3: "No olvides los márgenes.", teacherMsg4: "⚠️ Demasiados elementos reducen la conversión.",
    teacherMsg5: "¡Genial! Aplica la regla de los tercios.",
    promptExamples: "Ejemplos", prompt1: "Crear lección de diseño", prompt2: "Explicar tipografía", prompt3: "Hablar sobre teoría del color",
    slide1Title: "Diapositiva 1", slide1Sub: "Introducción", slide1Content: "Bienvenido al curso de diseño.",
    slide1B1: "Diseño UI/UX", slide1B2: "Herramientas", slide1B3: "Jerarquía visual", slide1B4: "Espacio de trabajo",
    slide2Title: "Diapositiva 2", slide2Sub: "Principios", slide2Content: "Principios clave de diseño.",
    slide2B1: "Contraste", slide2B2: "Cuadrículas", slide2B3: "Proximidad", slide2B4: "Repetición",
    slide3Title: "Diapositiva 3", slide3Sub: "Ejemplos prácticos", slide3Content: "Analicemos ejemplos reales.",
    slide3B1: "Análisis de apps", slide3B2: "Tu diseño", slide3B3: "Feedback IA", slide3B4: "Tarea final",
    keyTopics: "Temas clave:", slideIllustration: "Ilustración", prev: "Anterior", next: "Siguiente",
    metrics: "Métricas", detailedMetrics: "Métricas detalladas",
    overallProgress: "Progreso general", answerAccuracy: "Precisión", speed: "Velocidad", creativity: "Creatividad",
    teacherScore: "Puntuación del profesor", teacherFeedback: "¡Buen trabajo! Más tipografía.",
    lessons: "Lecciones", lesson1: "Diseño básico", lesson2: "Tipografía", lesson3: "Teoría del color", lesson4: "Componentes UI", lesson5: "Diseño responsivo",
    modelFast: "Rápido", modelPrecise: "Preciso", modelAdvanced: "Avanzado", modelBalanced: "Equilibrado",
    teacherAnalyzing: "El profesor analiza tu progreso...",
  },
  fr: {
    settings: "Paramètres", profile: "Profil", theme: "Thème", language: "Langue",
    midnightPurple: "Violet de minuit", deepOcean: "Océan profond", dark: "Sombre", light: "Clair",
    emeraldNight: "Nuit émeraude", sunsetWarm: "Coucher chaud", rosePink: "Rose",
    arctic: "Arctique", sandStorm: "Tempête de sable", cyberpunk: "Cyberpunk",
    typeMessage: "Tapez un message...", send: "Envoyer", copied: "Copié !",
    lessonTitle: "Leçon : Création de mise en page", lessonDesc: "Apprenez à créer des mises en page efficaces.",
    tasks: "Tâches :", task1: "Étudier les éléments de base", task2: "Créer un wireframe", task3: "Préparer un prototype Figma",
    aiTeacher: "Professeur IA", aiTeacherTips: "Professeur IA — Conseils",
    teacherMsg1: "Bienvenue dans la leçon !", teacherMsg2: "💡 Conseil : Commencez par la hiérarchie visuelle.",
    teacherMsg3: "N'oubliez pas les marges.", teacherMsg4: "⚠️ Trop d'éléments réduisent la conversion.",
    teacherMsg5: "Excellent ! Appliquez la règle des tiers.",
    promptExamples: "Exemples", prompt1: "Créer une leçon design", prompt2: "Expliquer la typographie", prompt3: "Parler de la théorie des couleurs",
    slide1Title: "Diapo 1", slide1Sub: "Introduction", slide1Content: "Bienvenue au cours de design.",
    slide1B1: "Design UI/UX", slide1B2: "Outils", slide1B3: "Hiérarchie visuelle", slide1B4: "Espace de travail",
    slide2Title: "Diapo 2", slide2Sub: "Principes", slide2Content: "Principes clés du design.",
    slide2B1: "Contraste", slide2B2: "Grilles", slide2B3: "Proximité", slide2B4: "Répétition",
    slide3Title: "Diapo 3", slide3Sub: "Exemples pratiques", slide3Content: "Analysons des exemples réels.",
    slide3B1: "Analyse d'apps", slide3B2: "Votre mise en page", slide3B3: "Feedback IA", slide3B4: "Tâche finale",
    keyTopics: "Sujets clés :", slideIllustration: "Illustration", prev: "Précédent", next: "Suivant",
    metrics: "Métriques", detailedMetrics: "Métriques détaillées",
    overallProgress: "Progrès global", answerAccuracy: "Précision", speed: "Vitesse", creativity: "Créativité",
    teacherScore: "Note du professeur", teacherFeedback: "Bon travail ! Plus de typographie.",
    lessons: "Leçons", lesson1: "Mise en page", lesson2: "Typographie", lesson3: "Couleurs", lesson4: "Composants UI", lesson5: "Design responsive",
    modelFast: "Rapide", modelPrecise: "Précis", modelAdvanced: "Avancé", modelBalanced: "Équilibré",
    teacherAnalyzing: "Le professeur analyse votre progrès...",
  },
  de: {
    settings: "Einstellungen", profile: "Profil", theme: "Thema", language: "Sprache",
    midnightPurple: "Mitternachtslila", deepOcean: "Tiefer Ozean", dark: "Dunkel", light: "Hell",
    emeraldNight: "Smaragdnacht", sunsetWarm: "Warmer Sonnenuntergang", rosePink: "Rosenrosa",
    arctic: "Arktisch", sandStorm: "Sandsturm", cyberpunk: "Cyberpunk",
    typeMessage: "Nachricht eingeben...", send: "Senden", copied: "Kopiert!",
    lessonTitle: "Lektion: Layout erstellen", lessonDesc: "Lernen Sie, effektive Layouts zu erstellen.",
    tasks: "Aufgaben:", task1: "Grundelemente lernen", task2: "Wireframe erstellen", task3: "Figma-Prototyp vorbereiten",
    aiTeacher: "KI-Lehrer", aiTeacherTips: "KI-Lehrer — Tipps",
    teacherMsg1: "Willkommen zur Lektion!", teacherMsg2: "💡 Tipp: Beginnen Sie mit der visuellen Hierarchie.",
    teacherMsg3: "Vergessen Sie nicht die Abstände.", teacherMsg4: "⚠️ Zu viele Elemente senken die Konversion.",
    teacherMsg5: "Großartig! Wenden Sie die Drittelregel an.",
    promptExamples: "Prompt-Beispiele", prompt1: "Design-Lektion erstellen", prompt2: "Typografie erklären", prompt3: "Über Farbtheorie erzählen",
    slide1Title: "Folie 1", slide1Sub: "Einführung", slide1Content: "Willkommen zum Designkurs.",
    slide1B1: "UI/UX Design", slide1B2: "Werkzeuge", slide1B3: "Visuelle Hierarchie", slide1B4: "Arbeitsbereich",
    slide2Title: "Folie 2", slide2Sub: "Grundprinzipien", slide2Content: "Wichtige Designprinzipien.",
    slide2B1: "Kontrast", slide2B2: "Raster", slide2B3: "Nähe", slide2B4: "Wiederholung",
    slide3Title: "Folie 3", slide3Sub: "Praktische Beispiele", slide3Content: "Analysieren wir reale Beispiele.",
    slide3B1: "App-Analyse", slide3B2: "Ihr Layout", slide3B3: "KI-Feedback", slide3B4: "Abschlussaufgabe",
    keyTopics: "Schlüsselthemen:", slideIllustration: "Illustration", prev: "Zurück", next: "Weiter",
    metrics: "Metriken", detailedMetrics: "Detaillierte Metriken",
    overallProgress: "Gesamtfortschritt", answerAccuracy: "Genauigkeit", speed: "Geschwindigkeit", creativity: "Kreativität",
    teacherScore: "Lehrerbewertung", teacherFeedback: "Gute Arbeit! Mehr Typografie.",
    lessons: "Lektionen", lesson1: "Layout-Grundlagen", lesson2: "Typografie", lesson3: "Farbtheorie", lesson4: "UI-Komponenten", lesson5: "Responsives Design",
    modelFast: "Schnell", modelPrecise: "Präzise", modelAdvanced: "Erweitert", modelBalanced: "Ausgewogen",
    teacherAnalyzing: "Der Lehrer analysiert Ihren Fortschritt...",
  },
  zh: {
    settings: "设置", profile: "个人资料", theme: "主题", language: "语言",
    midnightPurple: "午夜紫", deepOcean: "深海", dark: "暗色", light: "亮色",
    emeraldNight: "翡翠之夜", sunsetWarm: "暖色夕阳", rosePink: "玫瑰粉",
    arctic: "北极", sandStorm: "沙尘暴", cyberpunk: "赛博朋克",
    typeMessage: "输入消息...", send: "发送", copied: "已复制！",
    lessonTitle: "课程：创建布局", lessonDesc: "学习用现代设计方法创建有效的布局。",
    tasks: "任务：", task1: "学习基本元素", task2: "创建线框图", task3: "在Figma中准备原型",
    aiTeacher: "AI教师", aiTeacherTips: "AI教师 — 提示",
    teacherMsg1: "欢迎来到课程！", teacherMsg2: "💡 提示：从视觉层次开始。",
    teacherMsg3: "不要忘记留白。", teacherMsg4: "⚠️ 元素太多会降低转化率。", teacherMsg5: "很好！试试三分法则。",
    promptExamples: "提示示例", prompt1: "创建设计课程", prompt2: "解释排版", prompt3: "讲述色彩理论",
    slide1Title: "幻灯片1", slide1Sub: "简介", slide1Content: "欢迎来到设计课程。",
    slide1B1: "UI/UX设计", slide1B2: "工具", slide1B3: "视觉层次", slide1B4: "工作区",
    slide2Title: "幻灯片2", slide2Sub: "核心原则", slide2Content: "关键设计原则。",
    slide2B1: "对比", slide2B2: "网格", slide2B3: "邻近", slide2B4: "重复",
    slide3Title: "幻灯片3", slide3Sub: "实践示例", slide3Content: "分析真实案例。",
    slide3B1: "应用分析", slide3B2: "你的布局", slide3B3: "AI反馈", slide3B4: "最终任务",
    keyTopics: "关键主题：", slideIllustration: "插图", prev: "上一页", next: "下一页",
    metrics: "指标", detailedMetrics: "详细指标",
    overallProgress: "总体进度", answerAccuracy: "准确度", speed: "速度", creativity: "创造力",
    teacherScore: "教师评分", teacherFeedback: "做得好！注意排版。",
    lessons: "课程", lesson1: "布局基础", lesson2: "排版", lesson3: "色彩理论", lesson4: "UI组件", lesson5: "响应式设计",
    modelFast: "快速", modelPrecise: "精确", modelAdvanced: "高级", modelBalanced: "均衡",
    teacherAnalyzing: "教师正在分析你的进度...",
  },
    ar: {
    settings: "الإعدادات", profile: "الملف الشخصي", theme: "السمة", language: "اللغة",
    midnightPurple: "بنفسجي منتصف الليل", deepOcean: "المحيط العميق", dark: "داكن", light: "فاتح",
    emeraldNight: "ليلة زمردية", sunsetWarm: "غروب دافئ", rosePink: "وردي",
    arctic: "قطبي", sandStorm: "عاصفة رملية", cyberpunk: "سايبربانك",
    typeMessage: "اكتب رسالة...", send: "إرسال", copied: "تم النسخ!",
    lessonTitle: "الدرس: إنشاء التخطيط", lessonDesc: "تعلم إنشاء تخطيطات فعالة.",
    tasks: "المهام:", task1: "دراسة العناصر الأساسية", task2: "إنشاء إطار سلكي", task3: "تحضير نموذج في فيجما",
    aiTeacher: "معلم الذكاء الاصطناعي", aiTeacherTips: "معلم AI — نصائح",
    teacherMsg1: "مرحباً بك في الدرس!", teacherMsg2: "💡 نصيحة: ابدأ بالتسلسل البصري.",
    teacherMsg3: "لا تنسَ الهوامش.", teacherMsg4: "⚠️ العناصر الكثيرة تقلل التحويل.", teacherMsg5: "ممتاز! جرّب قاعدة الأثلاث.",
    promptExamples: "أمثلة", prompt1: "أنشئ درس تصميم", prompt2: "اشرح الطباعة", prompt3: "تحدث عن نظرية الألوان",
    slide1Title: "شريحة 1", slide1Sub: "مقدمة", slide1Content: "مرحباً بك في دورة التصميم.",
    slide1B1: "تصميم UI/UX", slide1B2: "الأدوات", slide1B3: "التسلسل البصري", slide1B4: "مساحة العمل",
    slide2Title: "شريحة 2", slide2Sub: "المبادئ الأساسية", slide2Content: "مبادئ التصميم الرئيسية.",
    slide2B1: "التباين", slide2B2: "الشبكات", slide2B3: "القرب", slide2B4: "التكرار",
    slide3Title: "شريحة 3", slide3Sub: "أمثلة عملية", slide3Content: "تحليل أمثلة حقيقية.",
    slide3B1: "تحليل التطبيقات", slide3B2: "تخطيطك", slide3B3: "تقييم AI", slide3B4: "المهمة النهائية",
    keyTopics: "المواضيع الرئيسية:", slideIllustration: "رسم توضيحي", prev: "السابق", next: "التالي",
    metrics: "المقاييس", detailedMetrics: "مقاييس مفصلة",
    overallProgress: "التقدم العام", answerAccuracy: "الدقة", speed: "السرعة", creativity: "الإبداع",
    teacherScore: "تقييم المعلم", teacherFeedback: "عمل جيد! اهتم بالطباعة أكثر.",
    lessons: "الدروس", lesson1: "أساسيات التخطيط", lesson2: "الطباعة", lesson3: "نظرية الألوان", lesson4: "مكونات UI", lesson5: "التصميم المتجاوب",
    modelFast: "سريع", modelPrecise: "دقيق", modelAdvanced: "متقدم", modelBalanced: "متوازن",
    teacherAnalyzing: "المعلم يحلل تقدمك...",
  },
  pt: {
    settings: "Configurações", profile: "Perfil", theme: "Tema", language: "Idioma",
    midnightPurple: "Roxo meia-noite", deepOcean: "Oceano profundo", dark: "Escuro", light: "Claro",
    emeraldNight: "Noite esmeralda", sunsetWarm: "Pôr do sol quente", rosePink: "Rosa",
    arctic: "Ártico", sandStorm: "Tempestade de areia", cyberpunk: "Cyberpunk",
    typeMessage: "Digite uma mensagem...", send: "Enviar", copied: "Copiado!",
    lessonTitle: "Lição: Criação de layout", lessonDesc: "Aprenda a criar layouts eficazes.",
    tasks: "Tarefas:", task1: "Estudar elementos básicos", task2: "Criar wireframe", task3: "Preparar protótipo no Figma",
    aiTeacher: "Professor IA", aiTeacherTips: "Professor IA — Dicas",
    teacherMsg1: "Bem-vindo à lição!", teacherMsg2: "💡 Dica: Comece pela hierarquia visual.",
    teacherMsg3: "Não esqueça as margens.", teacherMsg4: "⚠️ Muitos elementos reduzem a conversão.", teacherMsg5: "Ótimo! Aplique a regra dos terços.",
    promptExamples: "Exemplos", prompt1: "Criar lição de design", prompt2: "Explicar tipografia", prompt3: "Falar sobre teoria das cores",
    slide1Title: "Slide 1", slide1Sub: "Introdução", slide1Content: "Bem-vindo ao curso de design.",
    slide1B1: "Design UI/UX", slide1B2: "Ferramentas", slide1B3: "Hierarquia visual", slide1B4: "Espaço de trabalho",
    slide2Title: "Slide 2", slide2Sub: "Princípios", slide2Content: "Princípios-chave de design.",
    slide2B1: "Contraste", slide2B2: "Grades", slide2B3: "Proximidade", slide2B4: "Repetição",
    slide3Title: "Slide 3", slide3Sub: "Exemplos práticos", slide3Content: "Analisemos exemplos reais.",
    slide3B1: "Análise de apps", slide3B2: "Seu layout", slide3B3: "Feedback IA", slide3B4: "Tarefa final",
    keyTopics: "Tópicos-chave:", slideIllustration: "Ilustração", prev: "Anterior", next: "Próximo",
    metrics: "Métricas", detailedMetrics: "Métricas detalhadas",
    overallProgress: "Progresso geral", answerAccuracy: "Precisão", speed: "Velocidade", creativity: "Criatividade",
    teacherScore: "Nota do professor", teacherFeedback: "Bom trabalho! Foque na tipografia.",
    lessons: "Lições", lesson1: "Básico de layout", lesson2: "Tipografia", lesson3: "Teoria das cores", lesson4: "Componentes UI", lesson5: "Design responsivo",
    modelFast: "Rápido", modelPrecise: "Preciso", modelAdvanced: "Avançado", modelBalanced: "Equilibrado",
    teacherAnalyzing: "O professor está analisando seu progresso...",
  },
  ja: {
    settings: "設定", profile: "プロフィール", theme: "テーマ", language: "言語",
    midnightPurple: "ミッドナイトパープル", deepOcean: "深海", dark: "ダーク", light: "ライト",
    emeraldNight: "エメラルドナイト", sunsetWarm: "暖かい夕日", rosePink: "ローズピンク",
    arctic: "アークティック", sandStorm: "サンドストーム", cyberpunk: "サイバーパンク",
    typeMessage: "メッセージを入力...", send: "送信", copied: "コピー済み！",
    lessonTitle: "レッスン：レイアウト作成", lessonDesc: "効果的なレイアウトの作り方を学びます。",
    tasks: "タスク：", task1: "基本要素を学ぶ", task2: "ワイヤーフレーム作成", task3: "Figmaプロトタイプ準備",
    aiTeacher: "AI教師", aiTeacherTips: "AI教師 — ヒント",
    teacherMsg1: "レッスンへようこそ！", teacherMsg2: "💡 ヒント：視覚的階層から始めましょう。",
    teacherMsg3: "余白を忘れずに。", teacherMsg4: "⚠️ 要素が多すぎるとコンバージョンが下がります。", teacherMsg5: "素晴らしい！三分割法を試してみて。",
    promptExamples: "プロンプト例", prompt1: "デザインレッスンを作成", prompt2: "タイポグラフィを説明", prompt3: "色彩理論について",
    slide1Title: "スライド1", slide1Sub: "はじめに", slide1Content: "デザインコースへようこそ。",
    slide1B1: "UI/UXデザイン", slide1B2: "ツール", slide1B3: "視覚的階層", slide1B4: "ワークスペース",
    slide2Title: "スライド2", slide2Sub: "基本原則", slide2Content: "デザインの重要な原則。",
    slide2B1: "コントラスト", slide2B2: "グリッド", slide2B3: "近接", slide2B4: "反復",
    slide3Title: "スライド3", slide3Sub: "実践例", slide3Content: "実際の例を分析しましょう。",
    slide3B1: "アプリ分析", slide3B2: "あなたのレイアウト", slide3B3: "AIフィードバック", slide3B4: "最終課題",
    keyTopics: "キートピック：", slideIllustration: "イラスト", prev: "前へ", next: "次へ",
    metrics: "メトリクス", detailedMetrics: "詳細メトリクス",
    overallProgress: "全体の進捗", answerAccuracy: "正確度", speed: "速度", creativity: "創造性",
    teacherScore: "教師の評価", teacherFeedback: "良い仕事です！タイポグラフィに注目を。",
    lessons: "レッスン", lesson1: "レイアウト基礎", lesson2: "タイポグラフィ", lesson3: "色彩理論", lesson4: "UIコンポーネント", lesson5: "レスポンシブデザイン",
    modelFast: "高速", modelPrecise: "精密", modelAdvanced: "高度", modelBalanced: "バランス",
    teacherAnalyzing: "教師が進捗を分析しています...",
  },
  ko: {
    settings: "설정", profile: "프로필", theme: "테마", language: "언어",
    midnightPurple: "미드나잇 퍼플", deepOcean: "깊은 바다", dark: "다크", light: "라이트",
    emeraldNight: "에메랄드 나이트", sunsetWarm: "따뜻한 석양", rosePink: "로즈 핑크",
    arctic: "아크틱", sandStorm: "샌드스톰", cyberpunk: "사이버펑크",
    typeMessage: "메시지 입력...", send: "전송", copied: "복사됨!",
    lessonTitle: "레슨: 레이아웃 만들기", lessonDesc: "효과적인 레이아웃을 만드는 법을 배웁니다.",
    tasks: "과제:", task1: "기본 요소 학습", task2: "와이어프레임 만들기", task3: "Figma 프로토타입 준비",
    aiTeacher: "AI 교사", aiTeacherTips: "AI 교사 — 팁",
    teacherMsg1: "레슨에 오신 걸 환영합니다!", teacherMsg2: "💡 팁: 시각적 계층부터 시작하세요.",
    teacherMsg3: "여백을 잊지 마세요.", teacherMsg4: "⚠️ 요소가 너무 많으면 전환율이 떨어집니다.", teacherMsg5: "훌륭해요! 삼분할 법칙을 적용해 보세요.",
    promptExamples: "프롬프트 예시", prompt1: "디자인 레슨 만들기", prompt2: "타이포그래피 설명", prompt3: "색채 이론 설명",
    slide1Title: "슬라이드 1", slide1Sub: "소개", slide1Content: "디자인 코스에 오신 걸 환영합니다.",
    slide1B1: "UI/UX 디자인", slide1B2: "도구", slide1B3: "시각적 계층", slide1B4: "작업 공간",
    slide2Title: "슬라이드 2", slide2Sub: "핵심 원칙", slide2Content: "주요 디자인 원칙.",
    slide2B1: "대비", slide2B2: "그리드", slide2B3: "근접", slide2B4: "반복",
    slide3Title: "슬라이드 3", slide3Sub: "실습 예제", slide3Content: "실제 예제를 분석합니다.",
    slide3B1: "앱 분석", slide3B2: "당신의 레이아웃", slide3B3: "AI 피드백", slide3B4: "최종 과제",
    keyTopics: "핵심 주제:", slideIllustration: "일러스트", prev: "이전", next: "다음",
    metrics: "메트릭", detailedMetrics: "상세 메트릭",
    overallProgress: "전체 진행률", answerAccuracy: "정확도", speed: "속도", creativity: "창의성",
    teacherScore: "교사 평가", teacherFeedback: "잘했어요! 타이포그래피에 집중하세요.",
    lessons: "레슨", lesson1: "레이아웃 기초", lesson2: "타이포그래피", lesson3: "색채 이론", lesson4: "UI 컴포넌트", lesson5: "반응형 디자인",
    modelFast: "빠름", modelPrecise: "정밀", modelAdvanced: "고급", modelBalanced: "균형",
    teacherAnalyzing: "교사가 진행 상황을 분석 중...",
  },
  it: {
    settings: "Impostazioni", profile: "Profilo", theme: "Tema", language: "Lingua",
    midnightPurple: "Viola mezzanotte", deepOcean: "Oceano profondo", dark: "Scuro", light: "Chiaro",
    emeraldNight: "Notte smeraldo", sunsetWarm: "Tramonto caldo", rosePink: "Rosa",
    arctic: "Artico", sandStorm: "Tempesta di sabbia", cyberpunk: "Cyberpunk",
    typeMessage: "Scrivi un messaggio...", send: "Invia", copied: "Copiato!",
    lessonTitle: "Lezione: Creazione layout", lessonDesc: "Impara a creare layout efficaci.",
    tasks: "Compiti:", task1: "Studiare elementi base", task2: "Creare wireframe", task3: "Preparare prototipo Figma",
    aiTeacher: "Insegnante IA", aiTeacherTips: "Insegnante IA — Suggerimenti",
    teacherMsg1: "Benvenuto alla lezione!", teacherMsg2: "💡 Suggerimento: Inizia con la gerarchia visiva.",
    teacherMsg3: "Non dimenticare i margini.", teacherMsg4: "⚠️ Troppi elementi riducono la conversione.", teacherMsg5: "Ottimo! Prova la regola dei terzi.",
    promptExamples: "Esempi", prompt1: "Crea lezione di design", prompt2: "Spiega la tipografia", prompt3: "Parla della teoria del colore",
    slide1Title: "Slide 1", slide1Sub: "Introduzione", slide1Content: "Benvenuto al corso di design.",
    slide1B1: "Design UI/UX", slide1B2: "Strumenti", slide1B3: "Gerarchia visiva", slide1B4: "Spazio di lavoro",
    slide2Title: "Slide 2", slide2Sub: "Principi base", slide2Content: "Principi chiave del design.",
    slide2B1: "Contrasto", slide2B2: "Griglie", slide2B3: "Prossimità", slide2B4: "Ripetizione",
    slide3Title: "Slide 3", slide3Sub: "Esempi pratici", slide3Content: "Analizziamo esempi reali.",
    slide3B1: "Analisi app", slide3B2: "Il tuo layout", slide3B3: "Feedback IA", slide3B4: "Compito finale",
    keyTopics: "Argomenti chiave:", slideIllustration: "Illustrazione", prev: "Precedente", next: "Successivo",
    metrics: "Metriche", detailedMetrics: "Metriche dettagliate",
    overallProgress: "Progresso generale", answerAccuracy: "Precisione", speed: "Velocità", creativity: "Creatività",
    teacherScore: "Voto insegnante", teacherFeedback: "Buon lavoro! Concentrati sulla tipografia.",
    lessons: "Lezioni", lesson1: "Basi del layout", lesson2: "Tipografia", lesson3: "Teoria del colore", lesson4: "Componenti UI", lesson5: "Design responsive",
    modelFast: "Veloce", modelPrecise: "Preciso", modelAdvanced: "Avanzato", modelBalanced: "Bilanciato",
    teacherAnalyzing: "L'insegnante sta analizzando il tuo progresso...",
  },
  tr: {
    settings: "Ayarlar", profile: "Profil", theme: "Tema", language: "Dil",
    midnightPurple: "Gece yarısı moru", deepOcean: "Derin okyanus", dark: "Karanlık", light: "Aydınlık",
    emeraldNight: "Zümrüt gece", sunsetWarm: "Sıcak gün batımı", rosePink: "Gül pembesi",
    arctic: "Arktik", sandStorm: "Kum fırtınası", cyberpunk: "Siberpunk",
    typeMessage: "Mesaj yazın...", send: "Gönder", copied: "Kopyalandı!",
    lessonTitle: "Ders: Düzen oluşturma", lessonDesc: "Etkili düzenler oluşturmayı öğrenin.",
    tasks: "Görevler:", task1: "Temel öğeleri öğren", task2: "Wireframe oluştur", task3: "Figma prototipi hazırla",
    aiTeacher: "AI Öğretmen", aiTeacherTips: "AI Öğretmen — İpuçları",
    teacherMsg1: "Derse hoş geldiniz!", teacherMsg2: "💡 İpucu: Görsel hiyerarşi ile başlayın.",
    teacherMsg3: "Kenar boşluklarını unutmayın.", teacherMsg4: "⚠️ Çok fazla öğe dönüşümü azaltır.", teacherMsg5: "Harika! Üçler kuralını deneyin.",
    promptExamples: "Örnekler", prompt1: "Tasarım dersi oluştur", prompt2: "Tipoğrafiyi açıkla", prompt3: "Renk teorisini anlat",
    slide1Title: "Slayt 1", slide1Sub: "Giriş", slide1Content: "Tasarım kursuna hoş geldiniz.",
    slide1B1: "UI/UX Tasarım", slide1B2: "Araçlar", slide1B3: "Görsel hiyerarşi", slide1B4: "Çalışma alanı",
    slide2Title: "Slayt 2", slide2Sub: "Temel ilkeler", slide2Content: "Tasarımın temel ilkeleri.",
    slide2B1: "Kontrast", slide2B2: "Izgaralar", slide2B3: "Yakınlık", slide2B4: "Tekrar",
    slide3Title: "Slayt 3", slide3Sub: "Pratik örnekler", slide3Content: "Gerçek örnekleri analiz edelim.",
    slide3B1: "Uygulama analizi", slide3B2: "Sizin düzeniniz", slide3B3: "AI geri bildirimi", slide3B4: "Son görev",
    keyTopics: "Anahtar konular:", slideIllustration: "İllüstrasyon", prev: "Önceki", next: "Sonraki",
    metrics: "Metrikler", detailedMetrics: "Detaylı metrikler",
    overallProgress: "Genel ilerleme", answerAccuracy: "Doğruluk", speed: "Hız", creativity: "Yaratıcılık",
    teacherScore: "Öğretmen puanı", teacherFeedback: "İyi iş! Tipografiye odaklanın.",
    lessons: "Dersler", lesson1: "Düzen temelleri", lesson2: "Tipografi", lesson3: "Renk teorisi", lesson4: "UI bileşenleri", lesson5: "Duyarlı tasarım",
    modelFast: "Hızlı", modelPrecise: "Hassas", modelAdvanced: "Gelişmiş", modelBalanced: "Dengeli",
    teacherAnalyzing: "Öğretmen ilerlemenizi analiz ediyor...",
  },
  pl: {
    settings: "Ustawienia", profile: "Profil", theme: "Motyw", language: "Język",
    midnightPurple: "Północny fiolet", deepOcean: "Głęboki ocean", dark: "Ciemny", light: "Jasny",
    emeraldNight: "Szmaragdowa noc", sunsetWarm: "Ciepły zachód", rosePink: "Różowy",
    arctic: "Arktyczny", sandStorm: "Burza piaskowa", cyberpunk: "Cyberpunk",
    typeMessage: "Wpisz wiadomość...", send: "Wyślij", copied: "Skopiowano!",
    lessonTitle: "Lekcja: Tworzenie layoutu", lessonDesc: "Naucz się tworzyć efektywne layouty.",
    tasks: "Zadania:", task1: "Poznaj podstawowe elementy", task2: "Stwórz wireframe", task3: "Przygotuj prototyp w Figma",
    aiTeacher: "Nauczyciel AI", aiTeacherTips: "Nauczyciel AI — Wskazówki",
    teacherMsg1: "Witaj na lekcji!", teacherMsg2: "💡 Wskazówka: Zacznij od hierarchii wizualnej.",
    teacherMsg3: "Nie zapomnij o marginesach.", teacherMsg4: "⚠️ Za dużo elementów obniża konwersję.", teacherMsg5: "Świetnie! Zastosuj regułę tercji.",
    promptExamples: "Przykłady", prompt1: "Utwórz lekcję designu", prompt2: "Wyjaśnij typografię", prompt3: "Opowiedz o teorii koloru",
    slide1Title: "Slajd 1", slide1Sub: "Wprowadzenie", slide1Content: "Witaj na kursie designu.",
    slide1B1: "Design UI/UX", slide1B2: "Narzędzia", slide1B3: "Hierarchia wizualna", slide1B4: "Przestrzeń robocza",
    slide2Title: "Slajd 2", slide2Sub: "Zasady", slide2Content: "Kluczowe zasady designu.",
    slide2B1: "Kontrast", slide2B2: "Siatki", slide2B3: "Bliskość", slide2B4: "Powtórzenie",
    slide3Title: "Slajd 3", slide3Sub: "Przykłady praktyczne", slide3Content: "Przeanalizujmy realne przykłady.",
    slide3B1: "Analiza aplikacji", slide3B2: "Twój layout", slide3B3: "Feedback AI", slide3B4: "Zadanie końcowe",
    keyTopics: "Kluczowe tematy:", slideIllustration: "Ilustracja", prev: "Wstecz", next: "Dalej",
    metrics: "Metryki", detailedMetrics: "Szczegółowe metryki",
    overallProgress: "Ogólny postęp", answerAccuracy: "Dokładność", speed: "Szybkość", creativity: "Kreatywność",
    teacherScore: "Ocena nauczyciela", teacherFeedback: "Dobra robota! Skup się na typografii.",
    lessons: "Lekcje", lesson1: "Podstawy layoutu", lesson2: "Typografia", lesson3: "Teoria koloru", lesson4: "Komponenty UI", lesson5: "Responsywny design",
    modelFast: "Szybki", modelPrecise: "Precyzyjny", modelAdvanced: "Zaawansowany", modelBalanced: "Zrównoważony",
    teacherAnalyzing: "Nauczyciel analizuje twój postęp...",
  },
    uk: {
    settings: "Налаштування", profile: "Профіль", theme: "Тема", language: "Мова",
    midnightPurple: "Опівнічний фіолетовий", deepOcean: "Глибокий океан", dark: "Темна", light: "Світла",
    emeraldNight: "Смарагдова ніч", sunsetWarm: "Теплий захід", rosePink: "Рожева",
    arctic: "Арктична", sandStorm: "Піщана буря", cyberpunk: "Кіберпанк",
    typeMessage: "Введіть повідомлення...", send: "Надіслати", copied: "Скопійовано!",
    lessonTitle: "Урок: Створення макету", lessonDesc: "Навчіться створювати ефективні макети.",
    tasks: "Завдання:", task1: "Вивчити основні елементи", task2: "Створити wireframe", task3: "Підготувати прототип у Figma",
    aiTeacher: "AI Вчитель", aiTeacherTips: "AI Вчитель — Підказки",
    teacherMsg1: "Ласкаво просимо на урок!", teacherMsg2: "💡 Підказка: Почніть з візуальної ієрархії.",
    teacherMsg3: "Не забувайте про відступи.", teacherMsg4: "⚠️ Забагато елементів знижують конверсію.", teacherMsg5: "Чудово! Спробуйте правило третин.",
    promptExamples: "Приклади", prompt1: "Створити урок з дизайну", prompt2: "Пояснити типографіку", prompt3: "Розповісти про теорію кольору",
    slide1Title: "Слайд 1", slide1Sub: "Вступ", slide1Content: "Ласкаво просимо на курс дизайну.",
    slide1B1: "UI/UX дизайн", slide1B2: "Інструменти", slide1B3: "Візуальна ієрархія", slide1B4: "Робочий простір",
    slide2Title: "Слайд 2", slide2Sub: "Основні принципи", slide2Content: "Ключові принципи дизайну.",
    slide2B1: "Контраст", slide2B2: "Сітки", slide2B3: "Близькість", slide2B4: "Повторюваність",
    slide3Title: "Слайд 3", slide3Sub: "Практичні приклади", slide3Content: "Розберемо реальні приклади.",
    slide3B1: "Аналіз додатків", slide3B2: "Ваш макет", slide3B3: "Зворотний зв'язок AI", slide3B4: "Підсумкове завдання",
    keyTopics: "Ключові теми:", slideIllustration: "Ілюстрація", prev: "Назад", next: "Далі",
    metrics: "Метрики", detailedMetrics: "Детальні метрики",
    overallProgress: "Загальний прогрес", answerAccuracy: "Точність", speed: "Швидкість", creativity: "Креативність",
    teacherScore: "Оцінка вчителя", teacherFeedback: "Гарна робота! Зверніть увагу на типографіку.",
    lessons: "Уроки", lesson1: "Основи макету", lesson2: "Типографіка", lesson3: "Теорія кольору", lesson4: "UI компоненти", lesson5: "Адаптивний дизайн",
    modelFast: "Швидкий", modelPrecise: "Точний", modelAdvanced: "Просунутий", modelBalanced: "Збалансований",
    teacherAnalyzing: "Вчитель аналізує ваш прогрес...",
  },
  kk: {
    settings: "Баптаулар", profile: "Профиль", theme: "Тақырып", language: "Тіл",
    midnightPurple: "Түнгі күлгін", deepOcean: "Терең мұхит", dark: "Қараңғы", light: "Жарық",
    emeraldNight: "Зүмірет түн", sunsetWarm: "Жылы күнбатыс", rosePink: "Раушан",
    arctic: "Арктикалық", sandStorm: "Құм дауылы", cyberpunk: "Киберпанк",
    typeMessage: "Хабарлама жазыңыз...", send: "Жіберу", copied: "Көшірілді!",
    lessonTitle: "Сабақ: Макет жасау", lessonDesc: "Тиімді макеттер жасауды үйреніңіз.",
    tasks: "Тапсырмалар:", task1: "Негізгі элементтерді үйрену", task2: "Wireframe жасау", task3: "Figma прототипін дайындау",
    aiTeacher: "AI Мұғалім", aiTeacherTips: "AI Мұғалім — Кеңестер",
    teacherMsg1: "Сабаққа қош келдіңіз!", teacherMsg2: "💡 Кеңес: Визуалды иерархиядан бастаңыз.",
    teacherMsg3: "Шегіністерді ұмытпаңыз.", teacherMsg4: "⚠️ Тым көп элементтер конверсияны төмендетеді.", teacherMsg5: "Тамаша! Үштік ережесін қолданып көріңіз.",
    promptExamples: "Мысалдар", prompt1: "Дизайн сабағын жасау", prompt2: "Типографиканы түсіндіру", prompt3: "Түс теориясы туралы айту",
    slide1Title: "Слайд 1", slide1Sub: "Кіріспе", slide1Content: "Дизайн курсына қош келдіңіз.",
    slide1B1: "UI/UX дизайн", slide1B2: "Құралдар", slide1B3: "Визуалды иерархия", slide1B4: "Жұмыс кеңістігі",
    slide2Title: "Слайд 2", slide2Sub: "Негізгі принциптер", slide2Content: "Дизайнның негізгі принциптері.",
    slide2B1: "Контраст", slide2B2: "Торлар", slide2B3: "Жақындық", slide2B4: "Қайталау",
    slide3Title: "Слайд 3", slide3Sub: "Практикалық мысалдар", slide3Content: "Нақты мысалдарды талдаймыз.",
    slide3B1: "Қосымша талдау", slide3B2: "Сіздің макет", slide3B3: "AI кері байланыс", slide3B4: "Қорытынды тапсырма",
    keyTopics: "Негізгі тақырыптар:", slideIllustration: "Иллюстрация", prev: "Артқа", next: "Алға",
    metrics: "Метрикалар", detailedMetrics: "Толық метрикалар",
    overallProgress: "Жалпы прогресс", answerAccuracy: "Дәлдік", speed: "Жылдамдық", creativity: "Шығармашылық",
    teacherScore: "Мұғалім бағасы", teacherFeedback: "Жақсы жұмыс! Типографикаға назар аударыңыз.",
    lessons: "Сабақтар", lesson1: "Макет негіздері", lesson2: "Типографика", lesson3: "Түс теориясы", lesson4: "UI компоненттер", lesson5: "Адаптивті дизайн",
    modelFast: "Жылдам", modelPrecise: "Нақты", modelAdvanced: "Кеңейтілген", modelBalanced: "Теңдестірілген",
    teacherAnalyzing: "Мұғалім прогресіңізді талдап жатыр...",
  },
};

// ─── Theme Names for selector ────────────────────────────
export const themeNames: ThemeName[] = [
  "midnightPurple", "deepOcean", "dark", "light",
  "emeraldNight", "sunsetWarm", "rosePink",
  "arctic", "sandStorm", "cyberpunk",
];

export const languageNames: Record<Language, string> = {
  ru: "Русский", en: "English", es: "Español", fr: "Français",
  de: "Deutsch", zh: "中文", ar: "العربية", pt: "Português",
  ja: "日本語", ko: "한국어", it: "Italiano", tr: "Türkçe",
  pl: "Polski", uk: "Українська", kk: "Қазақша",
};

// ─── Context ─────────────────────────────────────────────
interface ThemeContextType {
  themeName: ThemeName;
  setThemeName: (name: ThemeName) => void;
  colors: ThemeColors;
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export function ThemeProvider({ children }: { children: ReactNode }) {
  const [themeName, setThemeName] = useState<ThemeName>(() => {
    const saved = localStorage.getItem("app-theme");
    return (saved as ThemeName) || "midnightPurple";
  });

  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "ru";
  });

  useEffect(() => {
    localStorage.setItem("app-theme", themeName);
  }, [themeName]);

  useEffect(() => {
    localStorage.setItem("app-language", language);
  }, [language]);

  const colors = themes[themeName];

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en?.[key] || key;
  };

  return (
    <ThemeContext.Provider value={{ themeName, setThemeName, colors, language, setLanguage, t }}>
      {children}
    </ThemeContext.Provider>
  );
}

export function useTheme() {
  const context = useContext(ThemeContext);
  if (!context) throw new Error("useTheme must be used within ThemeProvider");
  return context;
}